<?php

return [
    'hero' => [
        'eyebrow' => 'Hunarmand ustaxonasidan',
        'title' => "Qo'l mehnatida yaralgan san'at asarlari",
        'text' => "Suzani Shop interyer uchun nafis, sokin va qadrli mahsulotlar yaratadi. Har bir mahsulotda qo'l mehnati, iliq ranglar va sifatli materiallar orqali uyga hissiyot olib kiradigan ruh bor.",
        'primary_link' => '#catalog',
        'primary_label' => "Kolleksiyani ko'rish",
        'trust_note' => "Minimalistik ko'rinish, premium ishlov va hunarmand ruhini saqlagan maxsus kolleksiyalar.",
        'stats' => [
            ['label' => 'Amaliy tajriba', 'value' => '12 yil'],
            ['label' => "Qo'lda yaratilgan ish", 'value' => '5000+'],
            ['label' => 'Issiq va nafis kolleksiya', 'value' => 'Premium'],
        ],
        'promises' => [
            [
                'title' => 'Buyurtma asosida',
                'text' => "Har bir mahsulot interyer, rang va istakka moslab tayyorlanadi.",
            ],
            [
                'title' => 'Sifatli material',
                'text' => "Tabiiy mato, puxta ishlov va uzoq xizmat qiladigan detallarga e'tibor beriladi.",
            ],
            [
                'title' => "Butun dunyo bo'ylab yuborish",
                'text' => "Buyurtmalar ehtiyotkor qadoqlanib, ishonchli yetkazib berish bilan butun dunyoga jo'natiladi.",
            ],
        ],
        'main_image' => 'hero/hero-main.jpg',
        'meta' => [
            'hero_main_badge' => 'Asosiy kolleksiya',
            'hero_main_title' => 'Anor Suzani',
            'hero_main_caption' => "Katta format, mayin ranglar va qo'lda ishlangan nafis naqshlar.",
            'hero_detail_image' => 'hero/hero-detail.jpg',
            'hero_detail_badge' => 'Detail',
            'hero_detail_title' => 'Kashta teksturasi',
            'hero_material_image' => 'hero/suzani1.jpg',
            'hero_material_badge' => 'Material',
            'hero_material_title' => 'Ustaxona jarayoni va tabiiy mato',
        ],
    ],
    'about' => [
        'label' => 'Biz haqimizda',
        'title' => "Hunarmand tarixi, ustaxona ruhi va qo'lda yaratilgan har bir naqsh ortidagi mehnat",
        'lead' => "Suzani Shop faqat mahsulot sotmaydi. Biz har bir mahsulot orqali ustaning tajribasi, oilaviy hunarmandchilik yo'li va qo'lda ishlashga bo'lgan hurmatni yetkazamiz.",
        'gallery' => [
            [
                'src' => 'about/photo_2026-03-18_16-32-23.jpg',
                'label' => 'Ustaxona muhiti',
                'alt' => "Suzani Shop ustaxonasining ichki ko'rinishi",
            ],
            [
                'src' => 'items/photo_2026-03-18_16-32-05.jpg',
                'label' => 'Kashta detali',
                'alt' => 'Kashta naqshi yaqin planda',
            ],
            [
                'src' => 'items/photo_2026-03-18_16-32-08.jpg',
                'label' => 'Tayyor mahsulot',
                'alt' => 'Suzani Shop tayyor mahsuloti',
            ],
            [
                'src' => 'items/photo_2026-03-18_16-32-11.jpg',
                'label' => 'Material tanlovi',
                'alt' => 'Suzani Shop mahsuloti uchun tanlangan materiallar',
            ],
            [
                'src' => 'items/photo_2026-03-18_16-32-14.jpg',
                'label' => 'Yakuniy bezak',
                'alt' => "Suzani Shop mahsulotining yakuniy bezagi",
            ],
        ],
        'gallery_label' => 'Ustaxona galereyasi',
        'gallery_title' => "Jarayon, material va tayyor mahsulotlarning haqiqiy kadrlari",
        'gallery_caption' => 'Yuklangan rasmlar asosida',
        'gallery_description' => "Bu galereyada ustaxona ruhi, mato tanlovi va tayyor mahsulotlarning haqiqiy kadrlari jamlangan.",
        'note_label' => 'Mazmunli tanlov',
        'note_title' => "Mahsulot kartalariga ham shu yuklangan rasmlarning mos qismi biriktirildi",
        'note_text' => "Har bir kartochkada mahsulot turiga yaqin ko'rinishlar ko'rsatildi: devor suzanisi, stol bezagi, tekstil va sovg'a to'plamlari alohida guruhlandi.",
        'note_points' => [
            [
                'title' => 'Real kadrlar',
                'text' => "Placeholder o'rniga haqiqiy yuklangan suratlar ishlatiladi.",
            ],
            [
                'title' => 'Bir xil uslub',
                'text' => "About va product gallery bir xil vizual til bilan ishlaydi.",
            ],
            [
                'title' => 'Kattalashtirish',
                'text' => "Har bir rasmni modal oynada to'liq ko'rish mumkin.",
            ],
        ],
        'stats' => [
            ['label' => 'Tajriba', 'value' => '12 yil'],
            ['label' => "Qo'lda yaratilgan ishlar", 'value' => '5000+'],
            ['label' => 'Ustalar jamoasi', 'value' => '50 dan ziyot'],
        ],
        'highlights' => [
            [
                'title' => 'Hunarmand tarixi',
                'text' => "Ustamiz oilaviy kashtachilik an'anasida ulg'aygan. Birinchi ishlarini onasi va buvisidan o'rganib, keyinchalik zamonaviy interyer uchun suzani yaratishga ixtisoslashgan.",
            ],
            [
                'title' => 'Tajriba',
                'text' => "Ko'p yillik amaliy tajriba tufayli naqsh tanlash, rang muvozanati va mato sifatini bir joyga jamlay oladigan uslub shakllangan.",
            ],
            [
                'title' => 'Ustaxona',
                'text' => "Mahsulotlar kichik, lekin puxta tashkil etilgan ustaxonada tayyorlanadi. Har bir mahsulot kesish, tikish, kashta va yakuniy tekshiruv bosqichidan o'tadi.",
            ],
        ],
        'process_label' => "Qo'lda ishlash jarayoni",
        'process_title' => "Har bir mahsulot bir necha puxta bosqichdan o'tadi",
        'process' => [
            ['step' => '01', 'title' => 'Naqsh tanlash', 'text' => "Har mahsulot uchun interyerga mos kompozitsiya va rang palitrasi tanlanadi."],
            ['step' => '02', 'title' => 'Mato tayyorlash', 'text' => "Asosiy mato, astar va iplar sifat bo'yicha ajratilib, qo'lda ishlashga tayyorlanadi."],
            ['step' => '03', 'title' => "Qo'lda kashta", 'text' => "Asosiy bezaklar ustoz va jamoa tomonidan qo'lda, mayda detaligacha nazorat bilan ishlanadi."],
            ['step' => '04', 'title' => 'Yakuniy bezak', 'text' => "Mahsulot tozalanadi, tekshiriladi va mijozga yuborish uchun ehtiyotkor qadoqlanadi."],
        ],
        'why_label' => 'Nega aynan shu usta',
        'why_title' => "Ishonch, sifat va individual yondashuv sabab mijozlar yana qaytadi",
        'why_choose' => [
            "Har bir ish qo'lda bajariladi va nusxa ko'chirilgan ommaviy mahsulot emas.",
            "Material va ranglar mijoz interyeriga moslab tanlanishi mumkin.",
            "Usta bilan to'g'ridan-to'g'ri ishlash sababli buyurtma jarayoni aniq va ishonchli.",
            "Yakuniy mahsulot jo'natishdan oldin sifat bo'yicha alohida tekshiruvdan o'tadi.",
        ],
    ],
    'catalog' => [
        'gallery_labels' => ["Asosiy ko'rinish", "Detaldan ko'rinish", "Qo'shimcha ko'rinish", 'Material yaqindan', "Interyer ko'rinishi"],
        'gallery_fallback_pool' => [
            'items/photo_2026-03-18_16-31-05.jpg',
            'items/photo_2026-03-18_16-31-34.jpg',
            'items/photo_2026-03-18_16-31-39.jpg',
            'items/photo_2026-03-18_16-32-34.jpg',
            'items/photo_2026-03-18_16-32-47.jpg',
        ],
        'products_label' => 'Top mahsulotlar',
        'products_title' => "Eng ko'p tanlanayotgan mahsulotlar",
        'products_action_label' => 'Buyurtma berish',
        'collection_label' => 'Kategoriyalar / Barcha mahsulotlar',
        'collection_title' => "Har bir xonaga mos kolleksiyalar va qulay tanlov",
        'collection_copy' => "Kategoriya kartasining o'zini bosing. Sahifa yangilanmaydi, mahsulotlar shu joyning o'zida yumshoq almashadi va siz ortiqcha qadam qilmasdan tanlovni davom ettirasiz.",
        'collection_active_label' => 'Barchasi',
        'collection_active_copy' => "Barcha asosiy kolleksiyalar ochiq. Suzani, stol bezagi, tekstil va sovg'alarni bir joyda ko'ring.",
        'search_note' => "Mahsulot nomi, kategoriya yoki tavsif bo'yicha tez qidiring.",
        'filter_note' => "Bir teg bilan kerakli toifaga o'ting.",
        'sort_note' => "Natijalarni sizga qulay tartibda ko'ring.",
        'empty_state' => "Hozircha bu qidiruv yoki filter bo'yicha mahsulot topilmadi. Boshqa filter tanlab ko'ring.",
        'products' => [
            [
                'title' => 'Anor Suzani',
                'price' => 1250000,
                'tag' => "Qo'lda tikilgan",
                'short_description' => "Uy ichiga iliqlik olib kiradigan, qizil va oltin naqshli premium suzani.",
                'full_description' => "Anor Suzani katta devor kompozitsiyasi uchun mo'ljallangan bo'lib, markaziy gul naqshi va qo'lda bajarilgan mayda tikuvlar bilan ajralib turadi. Mehmonxona, kutubxona yoki mehmon kutish xonasiga boy kayfiyat beradi.",
                'product_story' => "Anor Suzani ustaxonaning qo'lda ishlangan kolleksiyasida an'anaviy naqsh va zamonaviy interyer ehtiyojlarini birlashtirish uchun yaratilgan. Har bir nusxa mayda detal va rang muvozanati bilan alohida ishlanadi.",
                'material' => 'Tabiiy paxta, ipak ip va atlas astar',
                'size' => '220 x 160 sm',
                'color' => 'Anor qizil, oltin va fil suyagi',
                'availability' => 'Buyurtma asosida mavjud',
                'lead_time' => '5-7 ish kuni',
                'category' => 'suzani',
                'category_label' => 'Devor uchun suzani',
                'category_description' => "Katta devor kompozitsiyasi va premium interyerlar uchun qo'lda tikilgan markaziy ishlar.",
                'popularity' => 98,
                'new_rank' => 8,
                'tone' => 'rose',
                'is_featured' => true,
                'gallery' => [
                    ['src' => 'items/il_794xN.6819611559_ozk7.jpg', 'label' => 'Asosiy kompozitsiya', 'alt' => "Anor Suzani asosiy ko'rinishi"],
                    ['src' => 'items/photo_2026-03-18_16-31-05.jpg', 'label' => 'Naqsh detali', 'alt' => 'Anor Suzani naqsh detali'],
                    ['src' => 'items/photo_2026-03-18_16-32-50.jpg', 'label' => "Interyer ko'rinishi", 'alt' => 'Anor Suzani interyer ichida'],
                ],
            ],
            [
                'title' => 'Samarqand Naqshi',
                'price' => 980000,
                'tag' => "Cheklangan to'plam",
                'short_description' => "Sharqona kompozitsiya va zamonaviy ranglar uyg'unlashgan dekor to'plami.",
                'full_description' => "Samarqand Naqshi o'zida tarixiy naqshlar va soddalashtirilgan kompozitsiyani jamlaydi. Ichki makonda milliy aksent yaratish uchun juda qulay va osish uchun tayyor holatda beriladi.",
                'product_story' => "Samarqand Naqshi tarixiy bezaklardan ilhomlangan bo'lib, uy interyeriga boy, ammo sokin kayfiyat olib kirish uchun ishlab chiqilgan.",
                'material' => 'Adras mato, paxta asos, ipak kashta',
                'size' => '180 x 130 sm',
                'color' => "Ko'k, terrakota va oq",
                'availability' => 'Omborda bor',
                'lead_time' => '1-2 ish kuni',
                'category' => 'suzani',
                'category_label' => 'Devor uchun suzani',
                'category_description' => "Katta devor kompozitsiyasi va premium interyerlar uchun qo'lda tikilgan markaziy ishlar.",
                'popularity' => 94,
                'new_rank' => 7,
                'tone' => 'ink',
                'is_featured' => true,
                'gallery' => [
                    ['src' => 'items/il_794xN.6819663333_8um2.jpg', 'label' => "Old ko'rinish", 'alt' => 'Samarqand Naqshi mahsuloti'],
                    ['src' => 'items/photo_2026-03-18_16-31-30.jpg', 'label' => 'Burchak detali', 'alt' => 'Samarqand Naqshi burchak detali'],
                ],
            ],
            [
                'title' => 'Baxmal Yostiq',
                'price' => 320000,
                'tag' => 'Top sotuv',
                'short_description' => "Suzani elementlari ishlangan baxmal yostiq uyga boy aksent beradi.",
                'full_description' => "Baxmal Yostiq yumshoq tekstura va nafis kashta bilan ishlab chiqilgan. Divan, kreslo yoki yotoqxona uchun oson moslashadi va juft holda buyurtma qilish mumkin.",
                'product_story' => "Baxmal Yostiq interyerga iliqlik va yumshoq kontrast beradigan eng talabgir tekstil ishlardan biri.",
                'material' => "Baxmal, paxta to'ldirma, kashta ip",
                'size' => '45 x 45 sm',
                'color' => 'Zumrad yashil va krem',
                'availability' => 'Omborda bor',
                'lead_time' => "24 soat ichida jo'natiladi",
                'category' => 'textile',
                'category_label' => 'Yostiq va tekstil',
                'category_description' => "Yumshoq tekstura, sokin rang va kashta aksenti bilan interyerga iliqlik beradigan kolleksiya.",
                'popularity' => 99,
                'new_rank' => 6,
                'tone' => 'teal',
                'is_featured' => true,
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-31-39.jpg', 'label' => "Asosiy ko'rinish", 'alt' => "Baxmal Yostiq asosiy ko'rinishi"],
                    ['src' => 'items/photo_2026-03-18_16-31-42.jpg', 'label' => 'Tekstura yaqindan', 'alt' => 'Baxmal Yostiq teksturasi yaqin planda'],
                ],
            ],
            [
                'title' => 'Atlas Stol Yugurigi',
                'price' => 410000,
                'tag' => 'Yangi',
                'short_description' => "Bayram dasturxoni va kundalik foydalanish uchun kashtali stol bezagi.",
                'full_description' => "Atlas Stol Yugurigi uzun stol uchun mo'ljallangan bo'lib, markaziy bezak sifatida interyerga jon bag'ishlaydi. Salfetka to'plami bilan uyg'un kombinatsiya hosil qiladi.",
                'product_story' => "Atlas Stol Yugurigi oilaviy dasturxon va mehmon kutish marosimlari uchun nafis aktsent sifatida ishlab chiqilgan.",
                'material' => 'Atlas, paxta asos, dekor ip',
                'size' => '150 x 40 sm',
                'color' => 'Asal sariq va oq',
                'availability' => 'Buyurtma asosida mavjud',
                'lead_time' => '3-4 ish kuni',
                'category' => 'table',
                'category_label' => 'Stol bezaklari',
                'category_description' => "Bayram dasturxoni va kundalik stol styling uchun nafis runner hamda bezaklar.",
                'popularity' => 89,
                'new_rank' => 9,
                'tone' => 'gold',
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-32-34.jpg', 'label' => "Stol ustidagi ko'rinish", 'alt' => 'Atlas Stol Yugurigi stol ustida'],
                    ['src' => 'items/photo_2026-03-18_16-32-37.jpg', 'label' => 'Kashta markazi', 'alt' => 'Atlas Stol Yugurigi kashta markazi'],
                ],
            ],
            [
                'title' => 'Buxoro Paneli',
                'price' => 1560000,
                'tag' => 'Premium',
                'short_description' => "Katta formatli suzani panel mehmonxona yoki ofis devori uchun mos.",
                'full_description' => "Buxoro Paneli yirik formatdagi dekor mahsulot bo'lib, maxsus buyurtma asosida qo'lda tayyorlanadi. Restoran, butik mehmonxona yoki premium uy interyerlari uchun tavsiya etiladi.",
                'product_story' => "Buxoro Paneli vakillik zonalari va premium uy interyerlariga moslashtirilgan yirik formatli ijodiy ishdir.",
                'material' => "Zich paxta, ipak ip, yog'och osma asos",
                'size' => '250 x 180 sm',
                'color' => 'Burgundi, qum rang va oltin',
                'availability' => "Oldindan buyurtma qilinadi",
                'lead_time' => '7-10 ish kuni',
                'category' => 'suzani',
                'category_label' => 'Devor uchun suzani',
                'category_description' => "Katta devor kompozitsiyasi va premium interyerlar uchun qo'lda tikilgan markaziy ishlar.",
                'popularity' => 91,
                'new_rank' => 5,
                'tone' => 'clay',
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-31-34.jpg', 'label' => 'Katta format', 'alt' => 'Buxoro Paneli katta formatda'],
                    ['src' => 'items/photo_2026-03-18_16-31-46.jpg', 'label' => 'Interyer ichida', 'alt' => 'Buxoro Paneli interyer ichida'],
                ],
            ],
            [
                'title' => "Ipak Sovg'a Box",
                'price' => 690000,
                'tag' => "Sovg'a",
                'short_description' => "Suzani detal va tekstil mahsulotlari jamlangan chiroyli sovg'a to'plami.",
                'full_description' => "Ipak Sovg'a Box ichida mini tekstil mahsulotlar, bezak elementlari va maxsus qadoq mavjud. To'y, mehmondorchilik yoki korporativ sovg'alar uchun mos variant.",
                'product_story' => "Ipak Sovg'a Box maxsus kunlar uchun estetik va milliy ruhdagi tayyor sovg'a formatidir.",
                'material' => "Ipak detal, paxta tekstil, qattiq qadoq",
                'size' => '35 x 28 sm quti',
                'color' => 'Pushti, krem va oltin',
                'availability' => 'Omborda bor',
                'lead_time' => '1 ish kuni',
                'category' => 'gift',
                'category_label' => "Sovg'a to'plamlari",
                'category_description' => "To'y, mehmondorchilik va maxsus kunlar uchun tayyorlangan sovg'abop premium setlar.",
                'popularity' => 87,
                'new_rank' => 4,
                'tone' => 'rose',
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-31-52.jpg', 'label' => "Qadoq ko'rinishi", 'alt' => "Ipak Sovg'a Box qadoq ko'rinishi"],
                    ['src' => 'items/photo_2026-03-18_16-31-56.jpg', 'label' => 'Ichki jamlanma', 'alt' => "Ipak Sovg'a Box ichki jamlanmasi"],
                ],
            ],
            [
                'title' => 'Kashta Runner Set',
                'price' => 540000,
                'tag' => 'Mashhur',
                'short_description' => "Stol uchun runner va salfetka to'plami zamonaviy interyerga juda mos.",
                'full_description' => "Kashta Runner Set oilaviy dasturxon, restoran yoki mehmon kutish stollari uchun qulay yechim. Minimal kompozitsiya va milliy bezak o'rtasida yaxshi muvozanat yaratadi.",
                'product_story' => "Kashta Runner Set mehmon kutish maydoni va family-style dasturxonlar uchun eng qulay ishlardan hisoblanadi.",
                'material' => "Paxta mato, atlas qirra, dekor kashta",
                'size' => "Runner 160 x 42 sm, 4 dona salfetka",
                'color' => 'Terrakota va bej',
                'availability' => 'Omborda bor',
                'lead_time' => '24-48 soat',
                'category' => 'table',
                'category_label' => 'Stol bezaklari',
                'category_description' => "Bayram dasturxoni va kundalik stol styling uchun nafis runner hamda bezaklar.",
                'popularity' => 96,
                'new_rank' => 3,
                'tone' => 'clay',
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-32-41.jpg', 'label' => "Set ko'rinishi", 'alt' => "Kashta Runner Set to'plami"],
                    ['src' => 'items/photo_2026-03-18_16-32-43.jpg', 'label' => 'Stol styling', 'alt' => 'Kashta Runner Set stol stylingi'],
                ],
            ],
            [
                'title' => 'Nafis Cushion Duo',
                'price' => 470000,
                'tag' => 'Chegirma',
                'short_description' => "Ikki dona yostiq jildi to'plami, yumshoq rang va kashta aksenti bilan.",
                'full_description' => "Nafis Cushion Duo yengil ranglar bilan ishlangan bo'lib, skandinavcha yoki klassik interyerga oson moslashadi. Juft kombinatsiya divan va yotoqxona bezagi sifatida ishlatiladi.",
                'product_story' => "Nafis Cushion Duo sokin ranglar va yumshoq tekstura bilan interyerga zamonaviy yengillik olib kiradi.",
                'material' => 'Paxta va baxmal aralash mato',
                'size' => '2 x 45 x 45 sm',
                'color' => "Sutli oq va osmon ko'k",
                'availability' => 'Omborda bor',
                'lead_time' => '1-2 ish kuni',
                'category' => 'textile',
                'category_label' => 'Yostiq va tekstil',
                'category_description' => "Yumshoq tekstura, sokin rang va kashta aksenti bilan interyerga iliqlik beradigan kolleksiya.",
                'popularity' => 90,
                'new_rank' => 2,
                'tone' => 'sky',
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-32-47.jpg', 'label' => "Juft kompozitsiya", 'alt' => 'Nafis Cushion Duo juft kompozitsiyasi'],
                    ['src' => 'items/photo_2026-03-18_16-32-50.jpg', 'label' => 'Yumshoq aktsent', 'alt' => 'Nafis Cushion Duo interyer aktsenti'],
                ],
            ],
            [
                'title' => "Navro'z Gift Set",
                'price' => 880000,
                'tag' => 'Yangi',
                'short_description' => "Maxsus tadbir va mehmonlar uchun tayyorlangan milliy sovg'a to'plami.",
                'full_description' => "Navro'z Gift Set tantanali kunlar, mehmonlar va yaqinlarga sovg'a qilish uchun tayyorlangan premium to'plam. Ichida dekor mahsulot, tekstil element va maxsus tabrik kartasi mavjud.",
                'product_story' => "Navro'z Gift Set milliy ruhdagi maxsus kunlar va ko'rgazmali taqdimotlar uchun yaratilgan.",
                'material' => "Aralash tekstil, ipak detal, premium qadoq",
                'size' => '40 x 30 sm quti',
                'color' => 'Yashil, oltin va oq',
                'availability' => 'Buyurtma asosida mavjud',
                'lead_time' => '3 ish kuni',
                'category' => 'gift',
                'category_label' => "Sovg'a to'plamlari",
                'category_description' => "To'y, mehmondorchilik va maxsus kunlar uchun tayyorlangan sovg'abop premium setlar.",
                'popularity' => 93,
                'new_rank' => 10,
                'tone' => 'teal',
                'gallery' => [
                    ['src' => 'items/photo_2026-03-18_16-31-59.jpg', 'label' => 'Bayram taqdimoti', 'alt' => "Navro'z Gift Set bayram taqdimoti"],
                    ['src' => 'items/photo_2026-03-18_16-32-02.jpg', 'label' => "Tarkib ko'rinishi", 'alt' => "Navro'z Gift Set tarkibi"],
                ],
            ],
        ],
    ],
    'portfolio' => [
        'label' => 'Portfolio / Galereya',
        'title' => "Real ishlar ishonch beradi, shu sabab bajarilgan loyihalarni ochiq ko'rsatamiz",
        'action_label' => "Shunga o'xshash buyurtma berish",
        'intro' => "Katalog mahsulotni ko'rsatadi, portfolio esa ustaning haqiqiy darajasini. Bu yerda turli interyerlar, maxsus buyurtmalar va tayyorlangan real ishlar uslubini ko'rishingiz mumkin.",
        'items' => [
            [
                'title' => 'Anor medalyon devor paneli',
                'type' => 'Premium interyer',
                'text' => "Katta mehmonxona yoki salon interyeri uchun chuqur bordo va tabiiy oltin ohanglarda tayyorlangan markaziy suzani kompozitsiyasi.",
                'tone' => 'clay',
                'highlight' => '260 x 190 sm',
                'image' => 'items/photo_2026-03-18_16-32-50.jpg',
            ],
            [
                'title' => "Kelin salom suzani jamlanmasi",
                'type' => "Shaxsiy buyurtma",
                'text' => "Yangi oila uchun yostiq, suzani va mayda tekstil aksentlardan tuzilgan, interyerga moslashtirilgan maxsus buyurtma seti.",
                'tone' => 'rose',
                'highlight' => 'Custom set',
                'image' => 'items/photo_2026-03-18_16-31-52.jpg',
            ],
            [
                'title' => 'Silk Road stol runner kolleksiyasi',
                'type' => 'HoReCa loyiha',
                'text' => "Milliy restoran va mehmon uylari uchun tikilgan runner hamda salfetka to'plami, ko'p martalik xizmatga mos zich matoda ishlangan.",
                'tone' => 'gold',
                'highlight' => "16 ta to'plam",
                'image' => 'items/photo_2026-03-18_16-31-46.jpg',
            ],
            [
                'title' => 'Boutique suite textile styling',
                'type' => 'Interyer styling',
                'text' => "Yotoqxona uchun yostiq, panel va yumshoq dekor uyg'unligida ishlab chiqilgan, pastel-baxmal ohangli kompozitsiya.",
                'tone' => 'sky',
                'highlight' => '4 element',
                'image' => 'items/photo_2026-03-18_16-32-08.jpg',
            ],
            [
                'title' => 'Reception zone naqsh paneli',
                'type' => 'Corporate decor',
                'text' => "Kutish zonasi va vakillik ofisi uchun brend kayfiyatiga moslashtirilgan, naqsh markazi kuchli dekorativ panel.",
                'tone' => 'ink',
                'highlight' => '220 x 150 sm',
                'image' => 'items/photo_2026-03-18_16-31-34.jpg',
            ],
            [
                'title' => "Navro'z ko'rgazma kompozitsiyasi",
                'type' => "Ko'rgazma namunasi",
                'text' => "Hunarmandchilik ko'rgazmasi va showroom namoyishi uchun tayyorlangan, yaqin masofada kashta sifatini ko'rsatadigan markaziy ish.",
                'tone' => 'teal',
                'highlight' => '210 x 140 sm',
                'image' => 'items/il_794xN.6819611559_ozk7.jpg',
            ],
        ],
    ],
    'steps' => [
        ['number' => '01', 'title' => 'Mahsulotni tanlang', 'text' => "Sizga yoqqan suzani yoki tekstil mahsulotini katalogdan tanlaysiz."],
        ['number' => '02', 'title' => "Buyurtma qoldiring", 'text' => "Telefon, Telegram yoki sayt formasi orqali bog'lanib buyurtmani tasdiqlaysiz."],
        ['number' => '03', 'title' => 'Tayyorlash va qadoqlash', 'text' => "Mahsulot tekshiriladi, ehtiyotkor qadoqlanadi va jo'natishga tayyorlanadi."],
        ['number' => '04', 'title' => 'Yetkazib berish', 'text' => "Buyurtmangiz butun dunyo bo'ylab ishonchli yetkazib berish xizmati bilan yuboriladi."],
    ],
    'testimonials' => [
        'label' => 'Mijoz fikrlari',
        'title' => 'Bizni tanlaganlar nima deydi',
        'items' => [
            [
                'name' => 'Dilnoza M.',
                'role' => 'Toshkent',
                'rating' => 5,
                'headline' => "Qadoqlanishi va mato sifati juda yoqdi",
                'badge' => 'Tasdiqlangan xarid',
                'quote' => "Mahsulot rasmdagidan ham chiroyli ekan. Qadoqlanishi va mato sifati juda yoqdi.",
            ],
            [
                'name' => 'Aziza R.',
                'role' => 'Samarqand',
                'rating' => 5,
                'headline' => "Interyerga yangi kayfiyat berdi",
                'badge' => 'Top sharh',
                'quote' => "Mehmonxona uchun olgan suzanim butun interyerga yangi kayfiyat berdi. Juda nafis ishlangan.",
            ],
            [
                'name' => 'Javohir K.',
                'role' => 'Buxoro',
                'rating' => 5,
                'headline' => "Tez yetkazildi va xizmat yaxshi",
                'badge' => 'Tasdiqlangan xarid',
                'quote' => "Onamga sovg'a qilgandim, juda xursand bo'ldilar. Tez yetib keldi va xizmat ham yaxshi.",
            ],
        ],
    ],
    'cta' => [
        'label' => 'Buyurtma uchun tayyormisiz',
        'title' => "Qo'lda ishlangan mahsulotni tanlang yoki Telegram orqali individual buyurtma yozing",
        'copy' => "Tayyor kolleksiyadan tanlash, maxsus o'lcham buyurtma qilish yoki ustadan maslahat olish uchun ikki qulay yo'lni ochiq qoldirdik.",
        'points' => [
            [
                'title' => 'Individual yondashuv',
                'text' => "Rang, o'lcham va kompozitsiya bo'yicha ustadan tavsiya oling.",
            ],
            [
                'title' => 'Tez aloqa',
                'text' => "So'rov yuborilgach, admin telefon yoki Telegram orqali bog'lanadi.",
            ],
            [
                'title' => "Butun dunyo bo'ylab",
                'text' => "Tayyor mahsulot va custom buyurtmalar butun dunyoga ehtiyotkor jo'natiladi.",
            ],
        ],
    ],
    'contact' => [
        'section_label' => 'Aloqa',
        'section_title' => "Buyurtma yoki hamkorlik uchun biz bilan bog'laning",
        'section_copy' => "Instagram, Telegram yoki telefon orqali murojaat qiling. Sizga mahsulot tanlash, rang moslashtirish va buyurtmani rasmiylashtirishda yordam beramiz.",
        'map_hint' => "Google Maps orqali joylashuvni ko'ring va marshrutni to'g'ridan-to'g'ri oching.",
        'meta' => [
            'phone_label' => 'Telefon',
            'phone_value' => '+99894 5450110',
            'telegram_label' => 'Telegram',
            'telegram_value' => '@mohitobon_art',
            'telegram_url' => 'https://t.me/mohitobon_art',
            'instagram_label' => 'Instagram',
            'instagram_value' => '@HANDMADE_BY_MUSHARRAF',
            'instagram_url' => 'https://www.instagram.com/handmade_by_musharraf?igsh=eWVtdHNia2s2M2Mz',
            'address_label' => 'Manzil',
            'address_value' => 'Shofirkon tumani',
            'hours_label' => 'Ish vaqti',
            'hours_value' => 'Dushanba - Shanba, 09:00 - 19:00',
            'map_label' => 'Xarita',
            'map_title' => 'Shofirkon markazi',
            'map_latitude' => 40.120000,
            'map_longitude' => 64.501400,
            'map_zoom' => 15,
            'form_label' => 'Forma',
            'form_title' => "Tezkor so'rov yuboring",
            'form_name_label' => 'Ismingiz',
            'form_name_placeholder' => "Ismingizni kiriting",
            'form_phone_label' => 'Telefon',
            'form_phone_placeholder' => '+99894 5450110',
            'form_social_label' => 'Instagram yoki Telegram',
            'form_social_placeholder' => '@username yoki profil havolasi',
            'form_message_label' => 'Xabar',
            'form_message_placeholder' => "Qanday mahsulot yoki xizmat kerakligini yozing",
            'form_success_note' => "So'rovingiz qabul qilindi. Tez orada siz bilan bog'lanamiz.",
        ],
    ],
    'footer' => [
        'banner_kicker' => 'Hunarmand va online bozor',
        'banner_title' => "Qo'lda ishlangan mahsulotlarni iliq, premium va ishonchli usulda buyurtma qiling",
        'banner_copy' => "Suzani Shop landing page qulayligi, ustaxona ruhi va online bozor tezligini bitta joyga jamlaydi. Telegram, telefon yoki katalog orqali o'zingizga mos buyurtmani tez boshlashingiz mumkin.",
        'banner_points' => [
            "Qo'lda ishlangan kolleksiyalar",
            "Individual buyurtma va custom o'lcham",
            "Telegram, telefon va xarita orqali tezkor aloqa",
        ],
        'banner_stats' => [
            ['value' => '12 yil', 'label' => 'Amaliy tajriba'],
            ['value' => '5000+', 'label' => "Qo'lda yaratilgan ish"],
        ],
        'brand_kicker' => 'Suzani Shop',
        'brand_copy' => "Qo'lda ishlangan suzani, tekstil va sovg'abop mahsulotlarni zamonaviy ko'rinishda namoyish qilib, xaridor uchun iliq taassurot va qulay buyurtma yo'lini birlashtiramiz.",
        'brand_subtitle' => 'Hunarmand ruhi bilan yaratilgan online bozor',
        'brand_pills' => [
            "Qo'lda ishlangan",
            "Premium ko'rinish",
            'Custom buyurtma',
            'Yetkazib berish',
        ],
        'menu_groups' => [
            [
                'kicker' => 'Navigatsiya',
                'title' => 'Sahifalar',
                'items' => [
                    [
                        'href' => '#about',
                        'title' => 'Hunarmand haqida',
                        'text' => "Ustaxona, hikoya va mahorat bilan tanishing",
                    ],
                    [
                        'href' => '#products',
                        'title' => "Mashhur mahsulotlar",
                        'text' => "Top kolleksiyalar va e'tiborli mahsulotlar",
                    ],
                    [
                        'href' => '#catalog',
                        'title' => 'Katalog',
                        'text' => "Ko'proq mahsulotlarni tez ko'rib chiqing",
                    ],
                    [
                        'href' => '#portfolio',
                        'title' => 'Portfolio',
                        'text' => "Oldingi ishlar va tayyor loyihalar namoyishi",
                    ],
                ],
            ],
            [
                'kicker' => 'Savdo',
                'title' => "Buyurtma yo'li",
                'items' => [
                    [
                        'href' => '#cart',
                        'title' => 'Savatcha va buyurtma',
                        'text' => "Tanlangan mahsulotlarni bir joyda yuboring",
                    ],
                    [
                        'href' => '#catalog',
                        'title' => 'Mahsulot tanlash',
                        'text' => "Bir qatorda ko'proq mahsulot va variantlar",
                    ],
                    [
                        'href' => '#portfolio',
                        'title' => 'Individual loyiha',
                        'text' => "Interyer va o'lchamga mos maxsus buyurtma",
                    ],
                    [
                        'href' => '#contact',
                        'title' => 'Hamkorlik va aloqa',
                        'text' => "Admin bilan tezkor maslahat va yo'nalish",
                    ],
                ],
            ],
        ],
        'bottom_copy' => "Hunarmand mahsulotlarini premium ko'rinish, tezkor aloqa va ishonchli buyurtma oqimi bilan taqdim etamiz.",
        'bottom_pills' => [
            "Qo'lda ishlangan kolleksiya",
            "Landing + katalog uyg'unligi",
            'Tezkor admin aloqa',
        ],
    ],
];
